modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = "A valid URL to your issue tracker where people can open bug tickets"
license = "MIT License"

[[mods]]
modId = "justenoughcobblemon"
version = "${version}"
displayName = "JustEnoughCobblemon"
authors = "Me!"
description = '''
A Cobblemon Addon to see Pokemon drops and where they spawn
'''
#logoFile = ""

[[dependencies.justenoughcobblemon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.justenoughcobblemon]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.justenoughcobblemon]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.justenoughcobblemon]]
modId = "jei"
mandatory = false
versionRange = "[19.0,)"
ordering = "AFTER"
side = "CLIENT"